// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_aPFADG-urQVH1jhlKHFmrYLJ7EtEk8c',
    appId: '1:248000603021:web:31640e6ad2b161aaec53c4',
    messagingSenderId: '248000603021',
    projectId: 'fragrance-identity',
    authDomain: 'fragrance-identity.firebaseapp.com',
    storageBucket: 'fragrance-identity.firebasestorage.app',
    measurementId: 'G-S9Z4SQG7YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyH0rNMTAhR8ZKgqRs_fccAoYtCBrvHm0',
    appId: '1:248000603021:android:4565d68689a266b5ec53c4',
    messagingSenderId: '248000603021',
    projectId: 'fragrance-identity',
    storageBucket: 'fragrance-identity.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1wEDJX6MsupLvBxWBPqNKpWWVXwDSsiA',
    appId: '1:248000603021:ios:ba637aac5d021081ec53c4',
    messagingSenderId: '248000603021',
    projectId: 'fragrance-identity',
    storageBucket: 'fragrance-identity.firebasestorage.app',
    iosBundleId: 'com.example.fragranceIdentityy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1wEDJX6MsupLvBxWBPqNKpWWVXwDSsiA',
    appId: '1:248000603021:ios:ba637aac5d021081ec53c4',
    messagingSenderId: '248000603021',
    projectId: 'fragrance-identity',
    storageBucket: 'fragrance-identity.firebasestorage.app',
    iosBundleId: 'com.example.fragranceIdentityy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_aPFADG-urQVH1jhlKHFmrYLJ7EtEk8c',
    appId: '1:248000603021:web:d97e2bcee586e946ec53c4',
    messagingSenderId: '248000603021',
    projectId: 'fragrance-identity',
    authDomain: 'fragrance-identity.firebaseapp.com',
    storageBucket: 'fragrance-identity.firebasestorage.app',
    measurementId: 'G-8T73XSY5LZ',
  );
}
